/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查（含数据库连通性） */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 邮箱注册，并直接登录当前设备 */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 邮箱密码登录，为当前设备签发令牌 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用 Refresh Token 换一对新令牌（轮换）
         * @description 旧的 Refresh Token 立即失效。如果同一个旧 Token 被再次使用（可能已泄露），
         *     该设备会被吊销，需要重新登录。
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 退出登录，吊销当前设备 */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户 */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 修改密码，并让其他设备全部退出 */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已登录的设备 */
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 让某台设备退出登录 */
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 拉取自 since 以来服务端变化的便利贴和看板（含已删除的） */
        get: operations["syncPull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 上传本地改过的便利贴和看板，逐条比较新旧
         * @description 对每条改动：服务端自客户端上次同步后没变（base_version 相同），或客户端的
         *     updated_at 更晚，则写入（applied）；否则服务端更新（stale），返回服务端当前记录。
         *     看板先于便利贴处理，同一批里新建的看板可以直接被便利贴引用。
         */
        post: operations["syncPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 错误详情 */
        Problem: {
            /** @default about:blank */
            type: string;
            /** @description 给人看的简短说明 */
            title: string;
            status: number;
            detail?: string;
            code: components["schemas"]["ErrorCode"];
            /** @description 字段级校验错误，键是字段名 */
            fields?: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        ErrorCode: "bad_request" | "validation_failed" | "unauthorized" | "token_expired" | "invalid_credentials" | "email_taken" | "wrong_password" | "not_found" | "rate_limited" | "unavailable" | "internal";
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        /** @enum {string} */
        Platform: "web" | "extension" | "android" | "ios" | "other";
        /** @description 登录时上报的设备信息，用于设备列表展示 */
        DeviceInfo: {
            /** @example Chrome · macOS */
            name: string;
            platform: components["schemas"]["Platform"];
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            name?: string;
            device: components["schemas"]["DeviceInfo"];
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            device: components["schemas"]["DeviceInfo"];
        };
        RefreshRequest: {
            refresh_token: string;
        };
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        TokenPair: {
            access_token: string;
            /** Format: date-time */
            access_expires_at: string;
            refresh_token: string;
            /** Format: date-time */
            refresh_expires_at: string;
            /** @enum {string} */
            token_type: "Bearer";
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            /** Format: uuid */
            device_id: string;
            tokens: components["schemas"]["TokenPair"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            name: string;
            /** Format: date-time */
            created_at: string;
        };
        Device: {
            /** Format: uuid */
            id: string;
            name: string;
            platform: components["schemas"]["Platform"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_seen_at: string;
            /** @description 是否是发起请求的这台设备 */
            current: boolean;
        };
        /** @enum {string} */
        NoteColor: "lemon" | "peach" | "blossom" | "lavender" | "sky" | "mint" | "sand" | "paper";
        /** @description 便利贴内容（整条，不是补丁） */
        NoteData: {
            /** @description Tiptap 文档 JSON（type 为 doc） */
            content: {
                [key: string]: unknown;
            };
            color: components["schemas"]["NoteColor"];
            /** Format: double */
            pos_x: number;
            /** Format: double */
            pos_y: number;
            /** Format: double */
            width: number;
            /** Format: double */
            height: number;
            /** Format: int32 */
            z_index: number;
            pinned: boolean;
            archived: boolean;
            /**
             * Format: uuid
             * @description 所在看板；为空或看板不存在时在收件箱
             */
            board_id?: string | null;
        };
        Note: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            version: number;
            /**
             * Format: date-time
             * @description 最后一次编辑的时间
             */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            data: components["schemas"]["NoteData"];
        };
        NoteChange: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int64
             * @description 本地上次同步时的服务端版本，从未同步过为 0
             */
            base_version: number;
            /**
             * Format: date-time
             * @description 本地最后一次编辑的时间
             */
            updated_at: string;
            deleted: boolean;
            data?: components["schemas"]["NoteData"];
        };
        /** @description 看板（整条，不是补丁） */
        BoardData: {
            name: string;
            color: components["schemas"]["NoteColor"];
            /** @description 分数索引，按字节序排序 */
            sort_order: string;
        };
        Board: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            version: number;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            deleted_at?: string | null;
            data: components["schemas"]["BoardData"];
        };
        BoardChange: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            base_version: number;
            /** Format: date-time */
            updated_at: string;
            deleted: boolean;
            data?: components["schemas"]["BoardData"];
        };
        SyncPullResponse: {
            notes: components["schemas"]["Note"][];
            boards: components["schemas"]["Board"][];
            /**
             * Format: int64
             * @description 下次 pull 用的 since
             */
            server_version: number;
            /** @description 还有更多变化，接着用 server_version 拉取 */
            has_more: boolean;
        };
        SyncPushRequest: {
            notes: components["schemas"]["NoteChange"][];
            boards?: components["schemas"]["BoardChange"][];
        };
        SyncPushResult: {
            /** Format: uuid */
            id: string;
            /**
             * @description applied 已写入；stale 服务端更新，用 note 覆盖本地；invalid 数据不合规，丢弃本地改动
             * @enum {string}
             */
            status: "applied" | "stale" | "invalid";
            note?: components["schemas"]["Note"];
            reason?: string;
        };
        BoardPushResult: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "applied" | "stale" | "invalid";
            board?: components["schemas"]["Board"];
            reason?: string;
        };
        SyncPushResponse: {
            results: components["schemas"]["SyncPushResult"][];
            board_results: components["schemas"]["BoardPushResult"][];
            /** Format: int64 */
            server_version: number;
        };
    };
    responses: {
        /** @description 错误 */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 注册成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description 刷新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已退出 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description 已修改 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已吊销 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    syncPull: {
        parameters: {
            query: {
                /** @description 上次同步得到的 server_version，首次为 0 */
                since: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPullResponse"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    syncPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPushRequest"];
            };
        };
        responses: {
            /** @description 每条改动的处理结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPushResponse"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
}
