// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BoardPushResultStatus.
const (
	BoardPushResultStatusApplied BoardPushResultStatus = "applied"
	BoardPushResultStatusInvalid BoardPushResultStatus = "invalid"
	BoardPushResultStatusStale   BoardPushResultStatus = "stale"
)

// Valid indicates whether the value is a known member of the BoardPushResultStatus enum.
func (e BoardPushResultStatus) Valid() bool {
	switch e {
	case BoardPushResultStatusApplied:
		return true
	case BoardPushResultStatusInvalid:
		return true
	case BoardPushResultStatusStale:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	BadRequest         ErrorCode = "bad_request"
	EmailTaken         ErrorCode = "email_taken"
	Internal           ErrorCode = "internal"
	InvalidCredentials ErrorCode = "invalid_credentials"
	NotFound           ErrorCode = "not_found"
	RateLimited        ErrorCode = "rate_limited"
	TokenExpired       ErrorCode = "token_expired"
	Unauthorized       ErrorCode = "unauthorized"
	Unavailable        ErrorCode = "unavailable"
	ValidationFailed   ErrorCode = "validation_failed"
	WrongPassword      ErrorCode = "wrong_password"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case BadRequest:
		return true
	case EmailTaken:
		return true
	case Internal:
		return true
	case InvalidCredentials:
		return true
	case NotFound:
		return true
	case RateLimited:
		return true
	case TokenExpired:
		return true
	case Unauthorized:
		return true
	case Unavailable:
		return true
	case ValidationFailed:
		return true
	case WrongPassword:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for NoteColor.
const (
	Blossom  NoteColor = "blossom"
	Lavender NoteColor = "lavender"
	Lemon    NoteColor = "lemon"
	Mint     NoteColor = "mint"
	Paper    NoteColor = "paper"
	Peach    NoteColor = "peach"
	Sand     NoteColor = "sand"
	Sky      NoteColor = "sky"
)

// Valid indicates whether the value is a known member of the NoteColor enum.
func (e NoteColor) Valid() bool {
	switch e {
	case Blossom:
		return true
	case Lavender:
		return true
	case Lemon:
		return true
	case Mint:
		return true
	case Paper:
		return true
	case Peach:
		return true
	case Sand:
		return true
	case Sky:
		return true
	default:
		return false
	}
}

// Defines values for Platform.
const (
	Android   Platform = "android"
	Extension Platform = "extension"
	Ios       Platform = "ios"
	Other     Platform = "other"
	Web       Platform = "web"
)

// Valid indicates whether the value is a known member of the Platform enum.
func (e Platform) Valid() bool {
	switch e {
	case Android:
		return true
	case Extension:
		return true
	case Ios:
		return true
	case Other:
		return true
	case Web:
		return true
	default:
		return false
	}
}

// Defines values for SyncPushResultStatus.
const (
	SyncPushResultStatusApplied SyncPushResultStatus = "applied"
	SyncPushResultStatusInvalid SyncPushResultStatus = "invalid"
	SyncPushResultStatusStale   SyncPushResultStatus = "stale"
)

// Valid indicates whether the value is a known member of the SyncPushResultStatus enum.
func (e SyncPushResultStatus) Valid() bool {
	switch e {
	case SyncPushResultStatusApplied:
		return true
	case SyncPushResultStatusInvalid:
		return true
	case SyncPushResultStatusStale:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	DeviceId openapi_types.UUID `json:"device_id"`
	Tokens   TokenPair          `json:"tokens"`
	User     User               `json:"user"`
}

// Board defines model for Board.
type Board struct {
	// Data 看板（整条，不是补丁）
	Data      BoardData          `json:"data"`
	DeletedAt *time.Time         `json:"deleted_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt time.Time          `json:"updated_at"`
	Version   int64              `json:"version"`
}

// BoardChange defines model for BoardChange.
type BoardChange struct {
	BaseVersion int64 `json:"base_version"`

	// Data 看板（整条，不是补丁）
	Data      *BoardData         `json:"data,omitempty"`
	Deleted   bool               `json:"deleted"`
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// BoardData 看板（整条，不是补丁）
type BoardData struct {
	Color NoteColor `json:"color"`
	Name  string    `json:"name"`

	// SortOrder 分数索引，按字节序排序
	SortOrder string `json:"sort_order"`
}

// BoardPushResult defines model for BoardPushResult.
type BoardPushResult struct {
	Board  *Board                `json:"board,omitempty"`
	Id     openapi_types.UUID    `json:"id"`
	Reason *string               `json:"reason,omitempty"`
	Status BoardPushResultStatus `json:"status"`
}

// BoardPushResultStatus defines model for BoardPushResult.Status.
type BoardPushResultStatus string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	NewPassword     string `json:"new_password"`
}

// Device defines model for Device.
type Device struct {
	CreatedAt time.Time `json:"created_at"`

	// Current 是否是发起请求的这台设备
	Current    bool               `json:"current"`
	Id         openapi_types.UUID `json:"id"`
	LastSeenAt time.Time          `json:"last_seen_at"`
	Name       string             `json:"name"`
	Platform   Platform           `json:"platform"`
}

// DeviceInfo 登录时上报的设备信息，用于设备列表展示
type DeviceInfo struct {
	// Name Example: Chrome · macOS
	Name     string   `json:"name"`
	Platform Platform `json:"platform"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Device 登录时上报的设备信息，用于设备列表展示
	Device   DeviceInfo          `json:"device"`
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Note defines model for Note.
type Note struct {
	// Data 便利贴内容（整条，不是补丁）
	Data      NoteData           `json:"data"`
	DeletedAt *time.Time         `json:"deleted_at,omitempty"`
	Id        openapi_types.UUID `json:"id"`

	// UpdatedAt 最后一次编辑的时间
	UpdatedAt time.Time `json:"updated_at"`
	Version   int64     `json:"version"`
}

// NoteChange defines model for NoteChange.
type NoteChange struct {
	// BaseVersion 本地上次同步时的服务端版本，从未同步过为 0
	BaseVersion int64 `json:"base_version"`

	// Data 便利贴内容（整条，不是补丁）
	Data    *NoteData          `json:"data,omitempty"`
	Deleted bool               `json:"deleted"`
	Id      openapi_types.UUID `json:"id"`

	// UpdatedAt 本地最后一次编辑的时间
	UpdatedAt time.Time `json:"updated_at"`
}

// NoteColor defines model for NoteColor.
type NoteColor string

// NoteData 便利贴内容（整条，不是补丁）
type NoteData struct {
	Archived bool `json:"archived"`

	// BoardId 所在看板；为空或看板不存在时在收件箱
	BoardId *openapi_types.UUID `json:"board_id,omitempty"`
	Color   NoteColor           `json:"color"`

	// Content Tiptap 文档 JSON（type 为 doc）
	Content json.RawMessage `json:"content"`
	Height  float64         `json:"height"`
	Pinned  bool            `json:"pinned"`
	PosX    float64         `json:"pos_x"`
	PosY    float64         `json:"pos_y"`
	Width   float64         `json:"width"`
	ZIndex  int32           `json:"z_index"`
}

// Platform defines model for Platform.
type Platform string

// Problem RFC 9457 错误详情
type Problem struct {
	Code   ErrorCode `json:"code"`
	Detail *string   `json:"detail,omitempty"`

	// Fields 字段级校验错误，键是字段名
	Fields *map[string]string `json:"fields,omitempty"`
	Status int                `json:"status"`

	// Title 给人看的简短说明
	Title string  `json:"title"`
	Type  *string `json:"type,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	// Device 登录时上报的设备信息，用于设备列表展示
	Device   DeviceInfo          `json:"device"`
	Email    openapi_types.Email `json:"email"`
	Name     *string             `json:"name,omitempty"`
	Password string              `json:"password"`
}

// SyncPullResponse defines model for SyncPullResponse.
type SyncPullResponse struct {
	Boards []Board `json:"boards"`

	// HasMore 还有更多变化，接着用 server_version 拉取
	HasMore bool   `json:"has_more"`
	Notes   []Note `json:"notes"`

	// ServerVersion 下次 pull 用的 since
	ServerVersion int64 `json:"server_version"`
}

// SyncPushRequest defines model for SyncPushRequest.
type SyncPushRequest struct {
	Boards *[]BoardChange `json:"boards,omitempty"`
	Notes  []NoteChange   `json:"notes"`
}

// SyncPushResponse defines model for SyncPushResponse.
type SyncPushResponse struct {
	BoardResults  []BoardPushResult `json:"board_results"`
	Results       []SyncPushResult  `json:"results"`
	ServerVersion int64             `json:"server_version"`
}

// SyncPushResult defines model for SyncPushResult.
type SyncPushResult struct {
	Id     openapi_types.UUID `json:"id"`
	Note   *Note              `json:"note,omitempty"`
	Reason *string            `json:"reason,omitempty"`

	// Status applied 已写入；stale 服务端更新，用 note 覆盖本地；invalid 数据不合规，丢弃本地改动
	Status SyncPushResultStatus `json:"status"`
}

// SyncPushResultStatus applied 已写入；stale 服务端更新，用 note 覆盖本地；invalid 数据不合规，丢弃本地改动
type SyncPushResultStatus string

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessExpiresAt  time.Time          `json:"access_expires_at"`
	AccessToken      string             `json:"access_token"`
	RefreshExpiresAt time.Time          `json:"refresh_expires_at"`
	RefreshToken     string             `json:"refresh_token"`
	TokenType        TokenPairTokenType `json:"token_type"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	Name      string              `json:"name"`
}

// SyncPullParams defines parameters for SyncPull.
type SyncPullParams struct {
	// Since 上次同步得到的 server_version，首次为 0
	Since int64 `form:"since" json:"since"`
	Limit *int  `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = RefreshRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// SyncPushJSONRequestBody defines body for SyncPush for application/json ContentType.
type SyncPushJSONRequestBody = SyncPushRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login 邮箱密码登录，为当前设备签发令牌
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout 退出登录，吊销当前设备
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// RefreshTokens 用 Refresh Token 换一对新令牌（轮换）
	// (POST /auth/refresh)
	RefreshTokens(w http.ResponseWriter, r *http.Request)
	// Register 邮箱注册，并直接登录当前设备
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// GetHealth 健康检查（含数据库连通性）
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetMe 当前用户
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// ListDevices 已登录的设备
	// (GET /me/devices)
	ListDevices(w http.ResponseWriter, r *http.Request)
	// RevokeDevice 让某台设备退出登录
	// (DELETE /me/devices/{deviceId})
	RevokeDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID)
	// ChangePassword 修改密码，并让其他设备全部退出
	// (POST /me/password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
	// SyncPull 拉取自 since 以来服务端变化的便利贴和看板（含已删除的）
	// (GET /sync/pull)
	SyncPull(w http.ResponseWriter, r *http.Request, params SyncPullParams)
	// SyncPush 上传本地改过的便利贴和看板，逐条比较新旧
	// (POST /sync/push)
	SyncPush(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login 邮箱密码登录，为当前设备签发令牌
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout 退出登录，吊销当前设备
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshTokens 用 Refresh Token 换一对新令牌（轮换）
// (POST /auth/refresh)
func (_ Unimplemented) RefreshTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register 邮箱注册，并直接登录当前设备
// (POST /auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealth 健康检查（含数据库连通性）
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe 当前用户
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListDevices 已登录的设备
// (GET /me/devices)
func (_ Unimplemented) ListDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RevokeDevice 让某台设备退出登录
// (DELETE /me/devices/{deviceId})
func (_ Unimplemented) RevokeDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ChangePassword 修改密码，并让其他设备全部退出
// (POST /me/password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SyncPull 拉取自 since 以来服务端变化的便利贴和看板（含已删除的）
// (GET /sync/pull)
func (_ Unimplemented) SyncPull(w http.ResponseWriter, r *http.Request, params SyncPullParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SyncPush 上传本地改过的便利贴和看板，逐条比较新旧
// (POST /sync/push)
func (_ Unimplemented) SyncPush(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshTokens operation middleware
func (siw *ServerInterfaceWrapper) RefreshTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeDevice operation middleware
func (siw *ServerInterfaceWrapper) RevokeDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deviceId" -------------
	var deviceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "deviceId", chi.URLParam(r, "deviceId"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deviceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncPull operation middleware
func (siw *ServerInterfaceWrapper) SyncPull(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SyncPullParams

	// ------------- Required query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "since", r.URL.Query(), &params.Since, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "since"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncPull(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SyncPush operation middleware
func (siw *ServerInterfaceWrapper) SyncPush(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SyncPush(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/me/password", wrapper.ChangePassword)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/devices", wrapper.ListDevices)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me/devices/{deviceId}", wrapper.RevokeDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/sync/pull", wrapper.SyncPull)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/sync/push", wrapper.SyncPush)
	})

	return r
}

type ProblemApplicationProblemPlusJSONResponse Problem

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login422ApplicationProblemPlusJSONResponse Problem

func (response Login422ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse Problem

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response Logout401ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokensRequestObject struct {
	Body *RefreshTokensJSONRequestBody
}

type RefreshTokensResponseObject interface {
	VisitRefreshTokensResponse(w http.ResponseWriter) error
}

type RefreshTokens200JSONResponse TokenPair

func (response RefreshTokens200JSONResponse) VisitRefreshTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokens401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response RefreshTokens401ApplicationProblemPlusJSONResponse) VisitRefreshTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokens422ApplicationProblemPlusJSONResponse Problem

func (response RefreshTokens422ApplicationProblemPlusJSONResponse) VisitRefreshTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse AuthResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register409ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response Register409ApplicationProblemPlusJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register422ApplicationProblemPlusJSONResponse Problem

func (response Register422ApplicationProblemPlusJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type Register429ApplicationProblemPlusJSONResponse Problem

func (response Register429ApplicationProblemPlusJSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetHealth503ApplicationProblemPlusJSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse User

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListDevicesRequestObject struct {
}

type ListDevicesResponseObject interface {
	VisitListDevicesResponse(w http.ResponseWriter) error
}

type ListDevices200JSONResponse []Device

func (response ListDevices200JSONResponse) VisitListDevicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListDevices401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ListDevices401ApplicationProblemPlusJSONResponse) VisitListDevicesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeDeviceRequestObject struct {
	DeviceId openapi_types.UUID `json:"deviceId"`
}

type RevokeDeviceResponseObject interface {
	VisitRevokeDeviceResponse(w http.ResponseWriter) error
}

type RevokeDevice204Response struct {
}

func (response RevokeDevice204Response) VisitRevokeDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeDevice401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response RevokeDevice401ApplicationProblemPlusJSONResponse) VisitRevokeDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RevokeDevice404ApplicationProblemPlusJSONResponse Problem

func (response RevokeDevice404ApplicationProblemPlusJSONResponse) VisitRevokeDeviceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePasswordRequestObject struct {
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword204Response struct {
}

func (response ChangePassword204Response) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ChangePassword401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ChangePassword401ApplicationProblemPlusJSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePassword403ApplicationProblemPlusJSONResponse Problem

func (response ChangePassword403ApplicationProblemPlusJSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ChangePassword422ApplicationProblemPlusJSONResponse Problem

func (response ChangePassword422ApplicationProblemPlusJSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPullRequestObject struct {
	Params SyncPullParams
}

type SyncPullResponseObject interface {
	VisitSyncPullResponse(w http.ResponseWriter) error
}

type SyncPull200JSONResponse SyncPullResponse

func (response SyncPull200JSONResponse) VisitSyncPullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPull401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response SyncPull401ApplicationProblemPlusJSONResponse) VisitSyncPullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPull422ApplicationProblemPlusJSONResponse Problem

func (response SyncPull422ApplicationProblemPlusJSONResponse) VisitSyncPullResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPushRequestObject struct {
	Body *SyncPushJSONRequestBody
}

type SyncPushResponseObject interface {
	VisitSyncPushResponse(w http.ResponseWriter) error
}

type SyncPush200JSONResponse SyncPushResponse

func (response SyncPush200JSONResponse) VisitSyncPushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPush401ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response SyncPush401ApplicationProblemPlusJSONResponse) VisitSyncPushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SyncPush422ApplicationProblemPlusJSONResponse Problem

func (response SyncPush422ApplicationProblemPlusJSONResponse) VisitSyncPushResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login 邮箱密码登录，为当前设备签发令牌
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout 退出登录，吊销当前设备
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RefreshTokens 用 Refresh Token 换一对新令牌（轮换）
	// (POST /auth/refresh)
	RefreshTokens(ctx context.Context, request RefreshTokensRequestObject) (RefreshTokensResponseObject, error)
	// Register 邮箱注册，并直接登录当前设备
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// GetHealth 健康检查（含数据库连通性）
	// (GET /healthz)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetMe 当前用户
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// ListDevices 已登录的设备
	// (GET /me/devices)
	ListDevices(ctx context.Context, request ListDevicesRequestObject) (ListDevicesResponseObject, error)
	// RevokeDevice 让某台设备退出登录
	// (DELETE /me/devices/{deviceId})
	RevokeDevice(ctx context.Context, request RevokeDeviceRequestObject) (RevokeDeviceResponseObject, error)
	// ChangePassword 修改密码，并让其他设备全部退出
	// (POST /me/password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
	// SyncPull 拉取自 since 以来服务端变化的便利贴和看板（含已删除的）
	// (GET /sync/pull)
	SyncPull(ctx context.Context, request SyncPullRequestObject) (SyncPullResponseObject, error)
	// SyncPush 上传本地改过的便利贴和看板，逐条比较新旧
	// (POST /sync/push)
	SyncPush(ctx context.Context, request SyncPushRequestObject) (SyncPushResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshTokens operation middleware
func (sh *strictHandler) RefreshTokens(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokensRequestObject

	var body RefreshTokensJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshTokens(ctx, request.(RefreshTokensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshTokens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokensResponseObject); ok {
		if err := validResponse.VisitRefreshTokensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListDevices operation middleware
func (sh *strictHandler) ListDevices(w http.ResponseWriter, r *http.Request) {
	var request ListDevicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDevices(ctx, request.(ListDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDevicesResponseObject); ok {
		if err := validResponse.VisitListDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeDevice operation middleware
func (sh *strictHandler) RevokeDevice(w http.ResponseWriter, r *http.Request, deviceId openapi_types.UUID) {
	var request RevokeDeviceRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeDevice(ctx, request.(RevokeDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeDeviceResponseObject); ok {
		if err := validResponse.VisitRevokeDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(w http.ResponseWriter, r *http.Request) {
	var request ChangePasswordRequestObject

	var body ChangePasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx, request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		if err := validResponse.VisitChangePasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SyncPull operation middleware
func (sh *strictHandler) SyncPull(w http.ResponseWriter, r *http.Request, params SyncPullParams) {
	var request SyncPullRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SyncPull(ctx, request.(SyncPullRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SyncPull")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SyncPullResponseObject); ok {
		if err := validResponse.VisitSyncPullResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SyncPush operation middleware
func (sh *strictHandler) SyncPush(w http.ResponseWriter, r *http.Request) {
	var request SyncPushRequestObject

	var body SyncPushJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SyncPush(ctx, request.(SyncPushRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SyncPush")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SyncPushResponseObject); ok {
		if err := validResponse.VisitSyncPushResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fpfc9PIlv8qKu2+rSEOf+7u+I2BvXeZnXuHAm7Nw0AZxW5iDbLk0Z9AhkqVAyGRwYk9jOMQx8CESSD8",
	"swOTmxhHkKr7Vcbdkp/8Fba6W5IlW7bjQNi5Lyk77u5zzq/POf07p/smG5OSKUkEoqqwkZusDJSUJCqA",
	"fDknS2MCSOKPMUlUgajij1wqJfAxTuUlcSRFR/zH94ok4t+UWAIkOfzp32VwlY2w/zbSXn+E/qqMOOtO",
	"TU2F2DhQYjKfwsuxEbZZWLaqVRb/YI/Gi53S1MR5WzP8PSVLKSCrPFUzDib4GIjycfzlqiQnOZWNsJrG",
	"x9kQq06mABthFVXmxXF2KsSq0jUgKoNUvIhHneN4GU/RFCAPmvB3PAarLYMfNF4GcTbyHZ0Y8ijoir/s",
	"aiaNfQ9iKhbzpcTJ8QDzOHUgomTqGTyQICoAFcSjnOoDJM6p4IjKJwEbYkVNELgxAbARVdZAAEr7BFNL",
	"4VX7iuqaMwFkhafu4k7gRfVPJ9qDeVEF4wF4EiWc+T7pIQpTT1hPJzhxPMB3xjgFRPtplORFPqkl2Ui4",
	"W7vQgfcGz7FXG5MkAXDioYIeBKPP8k4sbS17wnnGttsfvGb5Hnq41zJ0tLiFHq62jGyjNo8eVK3V9UZt",
	"umVk2FAH/DFJkAaG1t8kFZwmA6dCrMglyTYmuRtfA3FcTbCRP4XJNjlfRwMgUyRZjUpynMaxX2uoz6LF",
	"TXPrCTQWW0YWZTPw9ZJ19xas59DCfVjPYS/wSDsxCF6iYsi2zSe7J57nNAUnOE1QA1zUSQsDnWwIH5IB",
	"Z6fsbqxUTtWIZCBix/+OZnyA11FUTsC28eIEJ/BeB+nnavaKQdbTuDzHKcp1SY6fBz9oQAnAIKbJMhDV",
	"aMoe2OEBx8LhABtFcL3vBI/P/NcgO7oU6Fg+yLYzJO0HGCODoZOmLb/be9GDKsw/xX9zP1n/2LGqO+jN",
	"LbM0Y+0tw9ymVfkA1+baCw6fbAROUaMKAOJQ6jpR2vVDSuBUvMRAiuCMC3QoO8LcxUJeTDt0bmPXe4/O",
	"ilelgHS2vAvfL6Kl7UbtLrq7jkElcDb2VtF0tWVkzcJGo75A/wn1JWt1A75ZNNfqXWnOgQPc4JIpfOqy",
	"pxOylATMP3eYJBf75oI/xYyGB2e0jwayE8MgdP5bliX5tBQH3mwwxsWjsh2oIZbkAUIGo1c5XiBZQhM5",
	"TU1IMv8jcClPFNxIEdFu8ojGZBAHospzgsKGWJDkeCGqctcAPo6uy5I47os2SY1elTQRf5Y5FUQFPsmr",
	"jrgJjqd8JkROZ1nkhIDcFGL/B3ACRrQzJLtznnRtcHLrk9e+lsZ5sWc6i7uZod/WeXxzysbHF4H0Pz7P",
	"OXbyRJCv7D9rdljoiPBshK17kNH4oD4Yf8Uz/9/pa0diLadhfqFRS6NXq6ZRtD78ZJZm0NJ2c2mLDf1B",
	"qS5hSvtkup3WvoLlTZzoXq3CfBa9XkdL29jg8jy8u2q+rJoZHZVfYUq3u4DKL+gYa2+uUaszYS8gn444",
	"BzjFJ+TNQfZ//J5/Sqbd5r2evCSAJFklBbhYAi8uSIoiJcmpNwHEOCk4lWuTdAewCIUjSTPFpXwMtI2L",
	"i3MXKo0Pe1B/bm1twdk7sPJuGGbPybEEP9FrxwintSv2jo3IpGF5w6kkVhq1uvm8jvQi/U+jNg9fP4Dl",
	"DbS0jf8Wthu722bljXd37O0fmCOGrz28TZB4nMcac8I5j9lUkt+gi3xK5VIMKs6h1V+Zry5887eWoWNl",
	"GBw6cSlG0fPvfoi9cWRcOmL/83tFEo+e567/FSgKNw6wKgnAjyc6EqSk0RMwyd2gkXcibBMJ56srRtSS",
	"YzQQU7wo9tqllKREbwyQMRoO+6Uccf7TLUpSopOfbrnrfJwe5R+JwI9RXoyDG51J+vixwUnacYh2sUch",
	"c2x1lHT3qy3NRT7UDpWgJHDOw/OcHHAdjGHCdEMFop1TODEuS8TteQmTKUlN9Ah2T0/P76fn/3ya+eLE",
	"yf9kaAvOqj5Ft+8EFOzxgbylzRpJ4lZt3tKlylUeCHGldzQFTOmo3F8voco/zPoz9Mtq80WWKt4yss1C",
	"BRdE5FeYn2cDYG0Tvu6zSeVVAQSUA7vLjXrdLN8zSzNmJW0+fm1Vt9CDhcAmI/kHXuEqR4p6lhuTNDUy",
	"JnDitYGnBlXAVTJEUQ/yjvPgqgyURE+iKdPfo4SCByDaIdg/PFjgOK+oQP6jUNuAdtDJ8JAUeJg+wHCE",
	"+MKkGDunCULv3jU5CMknXgVJZd9tHlsUJ8vcJDkPOCWalOQAt7X2HqByBq1swbUSzD2A2WLLyKKFdfNh",
	"2ixsMAqQJ4Ds0BMG3cvAXDGwYSBKKti/pqQWCFDULy+ActTuoVerTEoTBMYsbJilGUbhxRgIopgDsjNV",
	"OORg3CXbg1rvzesTXAfZO5udTxHXPkunnfQcby5Ow6O9z6UDQepvf1/njcqkbzkkDp6GZ4CTDLukR9Ue",
	"K3a73bDe5OgU6jC7a+0BWAb2ePdZwYh2gb2fwNtXh9cfe3afl4E7b+HsMryz3jJWSMeXcctAtLKFipu0",
	"98VgdRjr6ay5UqT1U8tYsZs7DFrcRPMVzNfzuvVshlQMT6Bx2y60Cu/g3Q1MYg6/xdy+yuuCnYvFgKLY",
	"rSllqA6nPbXXwRpyz9KDLD7o2HZ6ag7NcFD8EnByIO/rgMynfCgAhk4VAs3xaRGE/N/te9OPb3/3ZggH",
	"bf306FAH+ZYjyrnXaevfbTRJNTFN5tXJCzgg7URJ9uWURusV+u3PjoZffXuRtW+7yYlL99BdOaGqKXpT",
	"zgd2qS+ofOza5JEzEmOWZmCh2qil0cI6zP0KK6XGuwx6uI7q+Zahx6WYMkJKDRXEVE0GR5Nx5p/PjrWM",
	"zO/pW5fEv0jtKG8ZusSl+COYd44DsWVkGrUF5uJkClwgkhlYeYL0HXtkCoh4MNaXKtYyMs3b783CG1R+",
	"hYpzuEQvPEZ6nsi5JFqVNas63TJKp4jfMSRAW4b+1bcXW0Z29CQD9dnm/cctI4MKH2B5g7lyym4nkz5z",
	"hKFuzlzSwuHjMeKD5CO40jJWLok2J3aXPR5m4NpzerNHe/VWZRO+X8TrV3Po1SrUd1Bxs3n7fcMoWe8r",
	"aP4JHrz0DPP8l/fg/G9w7Q1a1In2jdp84/0eTn6nJekaD1pG9lsw9nt6GuXuN3a34f0scyqVYuCdN2Zh",
	"A+azjVoari+hch3q27b5tEwxdx83amlrrwBXHjFXer2puNIydKcwaxmZlpG9gvfkCmOXPrvL5sY9WM9B",
	"fQ0VX5uFDSKDdWsYj3ecOnfW01GMsOGjo0fDOBLs/WMj7PGj4aPHCblVE8RvRzhNTYwI0jhPslBKojQI",
	"RzPR9WycjdBWN0vjBijql1J8ss+LkeFeivja6FP+6FRlDVCu0H6xciwc/mSyfY9OAp6q2NdDeh7efYxx",
	"PBEe7bWkq2P76UuIPXHs2JDjvxhivCcRsZHvLodYRUsmOXmSjbDNWxWz8gZWZ81fpqkR5HSuw/c/w8w8",
	"DRHz9QeY+6mxu2ZmstiduHGFHBw4hV3Gi7uuIWlqX9/Av3ft0omAa/idt810Gs7Vh8dyymcdWcS1C+bv",
	"Ngtpr2l9zLEPOa89Hd1JkhUYX4phOpIEfHoLPSrT2G/UXqClZ/Y468lLODuPXq3SDNIydJirWrffw523",
	"6LeZZvktjfBLolVdt28ajRKeRExoGdlmOW09nW7OzaPiJjXQCXc/6rZ6F+lTo8OJzI7Ow2eOTc/zrO7A",
	"pPn8cwVmn0DDx4TfVdD8E3wiVN+h4iYNrpahO2dOpq9n0r5L71BzOjOHtt/+xs++Nnz0syVj9NsGnM16",
	"9/yLf6VkTNXH6erdtrmyhRbWaXwPzlsJcqP9I1ZmHAS4xV+Aal96H2I42hKC9oVQSvT6V1irYdxOho9/",
	"Gtzg9Dqs76Bf0+jxOs6k+Ze04oT1n629R810CaWf+UNKmVRUkLRho+S/F2J/BYeJlv1UtAurb/73I48+",
	"6i1mYQPpOx7Dk8A1eoQ2K5Wexn/NK+oZe8xHQrCvzo39RqqrY3MY6Oy8pUHlPuTpj9HITfrhbHyKEgEB",
	"0O5LZ96dkK4B2w7MnWUuCVQg42Vvspg4Ez7t1I8R1lmV7cyfIQ94A+rXqcv7pFSUOxzoFKQrHgRpq/Ic",
	"Pc67z8+8jKwH5N72fPDx5n8oeEiHXPBrxH0ddcHwN/YqqPDuYPAfP2TS4m4XVZLWA/QIsirP4Z3txm7R",
	"ftt2Z6N5e8Nm5wEbqEyKsZGUJgg904pzEdIdIJ3d//YDFPhhCeqb5ALA12DFRPhpEdNo++kJibEfNCBP",
	"toPMuTPYR4Tt58HKVOhmoBjyCI31Luve+JHWu+9e2yNiNEDE5UM8crouoj5Rgv0ov6N3TdbcC3rDwzR2",
	"19HDdbcJRS+rzNJM+xXK/az7xBzmX+L0pv/SXF4zSzOdR70Y8/tmv6IO0/FqDj1cpV3pllFydbDmXrit",
	"Lp9v5hfQ21WYe9AydO/zHsZcqcF8lhZySC+6k83SzCWx/fKHQStbaLmEo01fdnrtut0EJ7NXYP4p1Je7",
	"Gu866Y9TAbR71AbMJoubTmFIwYJ39EZ9oQ3i2oyZnyWVMa5QUeZdcy6Liptwt26WZuwpuWpjd50SUevJ",
	"y/ZcY9HTYwoKcSVxSKm58zbuMxecXZdhQVzX40RmaYYCbe7+jB6VP3NkNWp3G8Yv7lWLtTfXI4yyzXQe",
	"61wtWB9u46J56VlAGPlpuL+d/d1lnLhohqYZXZMFNsKOcCl+ZGKUxb/a690MrNl+T087vYxpt99kp1dS",
	"5+Dc2xGwHp7bqC24ZM6elQQBc+wHjsYDeEfHm/PkUXMuR4O5d3P8JE0rzpmC4cAru99JQTF1eer/AgAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
