// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, user_id, name, platform, refresh_token_hash, refresh_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, platform, refresh_token_hash, prev_refresh_token_hash, refresh_expires_at, created_at, last_seen_at, revoked_at
`

type CreateDeviceParams struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	Name             string
	Platform         string
	RefreshTokenHash []byte
	RefreshExpiresAt time.Time
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Platform,
		arg.RefreshTokenHash,
		arg.RefreshExpiresAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.RefreshTokenHash,
		&i.PrevRefreshTokenHash,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, email, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, password_changed_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
}

// 认证相关查询（sqlc 生成到 internal/repo）
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveDevice = `-- name: GetActiveDevice :one
SELECT id, user_id, name, platform, refresh_token_hash, prev_refresh_token_hash, refresh_expires_at, created_at, last_seen_at, revoked_at FROM devices
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type GetActiveDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 每个需要认证的请求都会检查设备是否仍有效，让退出登录、吊销设备立即生效
func (q *Queries) GetActiveDevice(ctx context.Context, arg GetActiveDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getActiveDevice, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.RefreshTokenHash,
		&i.PrevRefreshTokenHash,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDeviceByPrevRefreshHash = `-- name: GetDeviceByPrevRefreshHash :one
SELECT id, user_id, name, platform, refresh_token_hash, prev_refresh_token_hash, refresh_expires_at, created_at, last_seen_at, revoked_at FROM devices WHERE prev_refresh_token_hash = $1
`

func (q *Queries) GetDeviceByPrevRefreshHash(ctx context.Context, prevRefreshTokenHash []byte) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByPrevRefreshHash, prevRefreshTokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.RefreshTokenHash,
		&i.PrevRefreshTokenHash,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getDeviceByRefreshHashForUpdate = `-- name: GetDeviceByRefreshHashForUpdate :one
SELECT id, user_id, name, platform, refresh_token_hash, prev_refresh_token_hash, refresh_expires_at, created_at, last_seen_at, revoked_at FROM devices WHERE refresh_token_hash = $1 FOR UPDATE
`

func (q *Queries) GetDeviceByRefreshHashForUpdate(ctx context.Context, refreshTokenHash []byte) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByRefreshHashForUpdate, refreshTokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.RefreshTokenHash,
		&i.PrevRefreshTokenHash,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, password_changed_at, created_at, updated_at FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, password_changed_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const initUserSyncSeq = `-- name: InitUserSyncSeq :exec
INSERT INTO user_sync_seq (user_id) VALUES ($1)
`

func (q *Queries) InitUserSyncSeq(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, initUserSyncSeq, userID)
	return err
}

const listActiveDevices = `-- name: ListActiveDevices :many
SELECT id, user_id, name, platform, refresh_token_hash, prev_refresh_token_hash, refresh_expires_at, created_at, last_seen_at, revoked_at FROM devices
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_seen_at DESC
`

func (q *Queries) ListActiveDevices(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listActiveDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Platform,
			&i.RefreshTokenHash,
			&i.PrevRefreshTokenHash,
			&i.RefreshExpiresAt,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :execrows
UPDATE devices SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeDeviceParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeDevice, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherDevices = `-- name: RevokeOtherDevices :exec
UPDATE devices SET revoked_at = now()
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
`

type RevokeOtherDevicesParams struct {
	UserID uuid.UUID
	KeepID uuid.UUID
}

func (q *Queries) RevokeOtherDevices(ctx context.Context, arg RevokeOtherDevicesParams) error {
	_, err := q.db.Exec(ctx, revokeOtherDevices, arg.UserID, arg.KeepID)
	return err
}

const rotateDeviceRefreshToken = `-- name: RotateDeviceRefreshToken :execrows
UPDATE devices
SET prev_refresh_token_hash = refresh_token_hash,
    refresh_token_hash      = $1,
    refresh_expires_at      = $2,
    last_seen_at            = now()
WHERE id = $3
  AND refresh_token_hash = $4
  AND revoked_at IS NULL
`

type RotateDeviceRefreshTokenParams struct {
	NewHash   []byte
	ExpiresAt time.Time
	ID        uuid.UUID
	OldHash   []byte
}

func (q *Queries) RotateDeviceRefreshToken(ctx context.Context, arg RotateDeviceRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateDeviceRefreshToken,
		arg.NewHash,
		arg.ExpiresAt,
		arg.ID,
		arg.OldHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, password_changed_at = now(), updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
