// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"time"

	"github.com/google/uuid"
)

type Board struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          string
	Color         string
	SortOrder     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Version       int64
	FieldVersions []byte
}

type Device struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	Name                 string
	Platform             string
	RefreshTokenHash     []byte
	PrevRefreshTokenHash []byte
	RefreshExpiresAt     time.Time
	CreatedAt            time.Time
	LastSeenAt           time.Time
	RevokedAt            *time.Time
}

type ItemTag struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	TagID         uuid.UUID
	ItemType      string
	ItemID        uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Version       int64
	FieldVersions []byte
}

type Note struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	BoardID       uuid.NullUUID
	Title         string
	Content       []byte
	Color         string
	Pinned        bool
	Archived      bool
	PosX          float64
	PosY          float64
	Width         float64
	Height        float64
	ZIndex        int32
	SortOrder     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Version       int64
	FieldVersions []byte
}

type Tag struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          string
	Color         string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Version       int64
	FieldVersions []byte
}

type Todo struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	BoardID       uuid.NullUUID
	NoteID        uuid.NullUUID
	ParentID      uuid.NullUUID
	Title         string
	Done          bool
	DoneAt        *time.Time
	DueAt         *time.Time
	Priority      int16
	SortOrder     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     *time.Time
	Version       int64
	FieldVersions []byte
}

type User struct {
	ID                uuid.UUID
	Email             string
	PasswordHash      string
	Name              string
	PasswordChangedAt time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type UserSyncSeq struct {
	UserID      uuid.UUID
	LastVersion int64
}
