// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getNoteForUpdate = `-- name: GetNoteForUpdate :one
SELECT id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions FROM notes WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetNoteForUpdate(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteForUpdate, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoardID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Pinned,
		&i.Archived,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const getSyncSeq = `-- name: GetSyncSeq :one
SELECT last_version FROM user_sync_seq WHERE user_id = $1
`

func (q *Queries) GetSyncSeq(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSyncSeq, userID)
	var last_version int64
	err := row.Scan(&last_version)
	return last_version, err
}

const insertNote = `-- name: InsertNote :one
INSERT INTO notes (
    id, user_id, content, color, pinned, archived,
    pos_x, pos_y, width, height, z_index,
    created_at, updated_at, deleted_at, version
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    now(), $12, $13, $14
)
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type InsertNoteParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Content   []byte
	Color     string
	Pinned    bool
	Archived  bool
	PosX      float64
	PosY      float64
	Width     float64
	Height    float64
	ZIndex    int32
	UpdatedAt time.Time
	DeletedAt *time.Time
	Version   int64
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.Color,
		arg.Pinned,
		arg.Archived,
		arg.PosX,
		arg.PosY,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Version,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoardID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Pinned,
		&i.Archived,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const lockSyncSeq = `-- name: LockSyncSeq :one

SELECT last_version FROM user_sync_seq WHERE user_id = $1 FOR UPDATE
`

// 同步（docs/architecture.md §5）
// 推送时锁住用户的版本序列：同一用户的推送串行执行，版本号按提交顺序递增，
// 拉取游标不会跳过尚未提交的版本
func (q *Queries) LockSyncSeq(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, lockSyncSeq, userID)
	var last_version int64
	err := row.Scan(&last_version)
	return last_version, err
}

const markNoteDeleted = `-- name: MarkNoteDeleted :one
UPDATE notes SET updated_at = $2, deleted_at = $2, version = $3
WHERE id = $1
RETURNING id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type MarkNoteDeletedParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	Version   int64
}

func (q *Queries) MarkNoteDeleted(ctx context.Context, arg MarkNoteDeletedParams) (Note, error) {
	row := q.db.QueryRow(ctx, markNoteDeleted, arg.ID, arg.UpdatedAt, arg.Version)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoardID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Pinned,
		&i.Archived,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const pullNotes = `-- name: PullNotes :many
SELECT id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions FROM notes
WHERE user_id = $1 AND version > $2 AND version <= $3
ORDER BY version
LIMIT $4
`

type PullNotesParams struct {
	UserID  uuid.UUID
	Since   int64
	Upto    int64
	MaxRows int32
}

func (q *Queries) PullNotes(ctx context.Context, arg PullNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, pullNotes,
		arg.UserID,
		arg.Since,
		arg.Upto,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BoardID,
			&i.Title,
			&i.Content,
			&i.Color,
			&i.Pinned,
			&i.Archived,
			&i.PosX,
			&i.PosY,
			&i.Width,
			&i.Height,
			&i.ZIndex,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.FieldVersions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSyncSeq = `-- name: SetSyncSeq :exec
UPDATE user_sync_seq SET last_version = $2 WHERE user_id = $1
`

type SetSyncSeqParams struct {
	UserID      uuid.UUID
	LastVersion int64
}

func (q *Queries) SetSyncSeq(ctx context.Context, arg SetSyncSeqParams) error {
	_, err := q.db.Exec(ctx, setSyncSeq, arg.UserID, arg.LastVersion)
	return err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET
    content = $2, color = $3, pinned = $4, archived = $5,
    pos_x = $6, pos_y = $7, width = $8, height = $9, z_index = $10,
    updated_at = $11, deleted_at = $12, version = $13
WHERE id = $1
RETURNING id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type UpdateNoteParams struct {
	ID        uuid.UUID
	Content   []byte
	Color     string
	Pinned    bool
	Archived  bool
	PosX      float64
	PosY      float64
	Width     float64
	Height    float64
	ZIndex    int32
	UpdatedAt time.Time
	DeletedAt *time.Time
	Version   int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.Content,
		arg.Color,
		arg.Pinned,
		arg.Archived,
		arg.PosX,
		arg.PosY,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Version,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoardID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Pinned,
		&i.Archived,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}
