// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const boardOwnedBy = `-- name: BoardOwnedBy :one
SELECT EXISTS (SELECT 1 FROM boards WHERE id = $1 AND user_id = $2)
`

type BoardOwnedByParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// 便利贴引用的看板是否属于该用户（已删除的看板也算，便利贴照常保存）
func (q *Queries) BoardOwnedBy(ctx context.Context, arg BoardOwnedByParams) (bool, error) {
	row := q.db.QueryRow(ctx, boardOwnedBy, arg.ID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const detachNotesFromPurgedBoards = `-- name: DetachNotesFromPurgedBoards :execrows

UPDATE notes SET board_id = NULL
WHERE board_id IN (SELECT b.id FROM boards b WHERE b.deleted_at IS NOT NULL AND b.deleted_at < $1::timestamptz)
`

// 回收站清理（internal/jobs）：软删除超过保留期的记录彻底删除
// 看板硬删除会级联删除其中的便利贴：先把还在用的便利贴移到收件箱（客户端早已按收件箱显示）
func (q *Queries) DetachNotesFromPurgedBoards(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, detachNotesFromPurgedBoards, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBoardForUpdate = `-- name: GetBoardForUpdate :one
SELECT id, user_id, name, color, sort_order, created_at, updated_at, deleted_at, version, field_versions FROM boards WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBoardForUpdate(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardForUpdate, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const getNoteForUpdate = `-- name: GetNoteForUpdate :one
SELECT id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions FROM notes WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetNoteForUpdate(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteForUpdate, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoardID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Pinned,
		&i.Archived,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const getSyncSeq = `-- name: GetSyncSeq :one
SELECT last_version FROM user_sync_seq WHERE user_id = $1
`

func (q *Queries) GetSyncSeq(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSyncSeq, userID)
	var last_version int64
	err := row.Scan(&last_version)
	return last_version, err
}

const insertBoard = `-- name: InsertBoard :one
INSERT INTO boards (id, user_id, name, color, sort_order, created_at, updated_at, version)
VALUES ($1, $2, $3, $4, $5, now(), $6, $7)
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, name, color, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type InsertBoardParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	Color     string
	SortOrder string
	UpdatedAt time.Time
	Version   int64
}

func (q *Queries) InsertBoard(ctx context.Context, arg InsertBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, insertBoard,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Color,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const insertNote = `-- name: InsertNote :one
INSERT INTO notes (
    id, user_id, content, color, pinned, archived,
    pos_x, pos_y, width, height, z_index,
    created_at, updated_at, deleted_at, version, board_id
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    now(), $12, $13, $14, $15
)
ON CONFLICT (id) DO NOTHING
RETURNING id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type InsertNoteParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Content   []byte
	Color     string
	Pinned    bool
	Archived  bool
	PosX      float64
	PosY      float64
	Width     float64
	Height    float64
	ZIndex    int32
	UpdatedAt time.Time
	DeletedAt *time.Time
	Version   int64
	BoardID   uuid.NullUUID
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.Color,
		arg.Pinned,
		arg.Archived,
		arg.PosX,
		arg.PosY,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Version,
		arg.BoardID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoardID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Pinned,
		&i.Archived,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const lockSyncSeq = `-- name: LockSyncSeq :one

SELECT last_version FROM user_sync_seq WHERE user_id = $1 FOR UPDATE
`

// 同步（docs/architecture.md §5）
// 推送时锁住用户的版本序列：同一用户的推送串行执行，版本号按提交顺序递增，
// 拉取游标不会跳过尚未提交的版本
func (q *Queries) LockSyncSeq(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, lockSyncSeq, userID)
	var last_version int64
	err := row.Scan(&last_version)
	return last_version, err
}

const markBoardDeleted = `-- name: MarkBoardDeleted :one
UPDATE boards SET updated_at = $2, deleted_at = $2, version = $3
WHERE id = $1
RETURNING id, user_id, name, color, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type MarkBoardDeletedParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	Version   int64
}

func (q *Queries) MarkBoardDeleted(ctx context.Context, arg MarkBoardDeletedParams) (Board, error) {
	row := q.db.QueryRow(ctx, markBoardDeleted, arg.ID, arg.UpdatedAt, arg.Version)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const markNoteDeleted = `-- name: MarkNoteDeleted :one
UPDATE notes SET updated_at = $2, deleted_at = $2, version = $3
WHERE id = $1
RETURNING id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type MarkNoteDeletedParams struct {
	ID        uuid.UUID
	UpdatedAt time.Time
	Version   int64
}

func (q *Queries) MarkNoteDeleted(ctx context.Context, arg MarkNoteDeletedParams) (Note, error) {
	row := q.db.QueryRow(ctx, markNoteDeleted, arg.ID, arg.UpdatedAt, arg.Version)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoardID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Pinned,
		&i.Archived,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const pullBoards = `-- name: PullBoards :many
SELECT id, user_id, name, color, sort_order, created_at, updated_at, deleted_at, version, field_versions FROM boards
WHERE user_id = $1 AND version > $2 AND version <= $3
ORDER BY version
`

type PullBoardsParams struct {
	UserID uuid.UUID
	Since  int64
	Upto   int64
}

// 看板很少，一次取完 (since, upto] 区间内的全部变化
func (q *Queries) PullBoards(ctx context.Context, arg PullBoardsParams) ([]Board, error) {
	rows, err := q.db.Query(ctx, pullBoards, arg.UserID, arg.Since, arg.Upto)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.FieldVersions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pullNotes = `-- name: PullNotes :many
SELECT id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions FROM notes
WHERE user_id = $1 AND version > $2 AND version <= $3
ORDER BY version
LIMIT $4
`

type PullNotesParams struct {
	UserID  uuid.UUID
	Since   int64
	Upto    int64
	MaxRows int32
}

func (q *Queries) PullNotes(ctx context.Context, arg PullNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, pullNotes,
		arg.UserID,
		arg.Since,
		arg.Upto,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BoardID,
			&i.Title,
			&i.Content,
			&i.Color,
			&i.Pinned,
			&i.Archived,
			&i.PosX,
			&i.PosY,
			&i.Width,
			&i.Height,
			&i.ZIndex,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Version,
			&i.FieldVersions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDeletedBoards = `-- name: PurgeDeletedBoards :execrows
DELETE FROM boards WHERE deleted_at IS NOT NULL AND deleted_at < $1::timestamptz
`

func (q *Queries) PurgeDeletedBoards(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedBoards, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeDeletedNotes = `-- name: PurgeDeletedNotes :execrows
DELETE FROM notes WHERE deleted_at IS NOT NULL AND deleted_at < $1::timestamptz
`

func (q *Queries) PurgeDeletedNotes(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeletedNotes, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSyncSeq = `-- name: SetSyncSeq :exec
UPDATE user_sync_seq SET last_version = $2 WHERE user_id = $1
`

type SetSyncSeqParams struct {
	UserID      uuid.UUID
	LastVersion int64
}

func (q *Queries) SetSyncSeq(ctx context.Context, arg SetSyncSeqParams) error {
	_, err := q.db.Exec(ctx, setSyncSeq, arg.UserID, arg.LastVersion)
	return err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards SET
    name = $2, color = $3, sort_order = $4, updated_at = $5, deleted_at = NULL, version = $6
WHERE id = $1
RETURNING id, user_id, name, color, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type UpdateBoardParams struct {
	ID        uuid.UUID
	Name      string
	Color     string
	SortOrder string
	UpdatedAt time.Time
	Version   int64
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.SortOrder,
		arg.UpdatedAt,
		arg.Version,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET
    content = $2, color = $3, pinned = $4, archived = $5,
    pos_x = $6, pos_y = $7, width = $8, height = $9, z_index = $10,
    updated_at = $11, deleted_at = $12, version = $13, board_id = $14
WHERE id = $1
RETURNING id, user_id, board_id, title, content, color, pinned, archived, pos_x, pos_y, width, height, z_index, sort_order, created_at, updated_at, deleted_at, version, field_versions
`

type UpdateNoteParams struct {
	ID        uuid.UUID
	Content   []byte
	Color     string
	Pinned    bool
	Archived  bool
	PosX      float64
	PosY      float64
	Width     float64
	Height    float64
	ZIndex    int32
	UpdatedAt time.Time
	DeletedAt *time.Time
	Version   int64
	BoardID   uuid.NullUUID
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.ID,
		arg.Content,
		arg.Color,
		arg.Pinned,
		arg.Archived,
		arg.PosX,
		arg.PosY,
		arg.Width,
		arg.Height,
		arg.ZIndex,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.Version,
		arg.BoardID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BoardID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Pinned,
		&i.Archived,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.ZIndex,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Version,
		&i.FieldVersions,
	)
	return i, err
}
